version: "3.8"

services:
  backend:
    build: ../backend
    volumes:
      - ../backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - ../backend/.env

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    posts:
      - "8000:80"
    volume:
      - ./nginx.conf:/etc/nginx/nginx.cong:ro

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: exness
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
