events {}

http {
    upstream backend {
        server app1:4500;
        server app2:4501;
    }

    server{
        listen 80;
        location / {
            proxy_pass http://backend;
            # proxy_pass http://localhost:4500;
        }
    }
}