syntax = "proto3";

package candles;

service CandleService {
    rpc GetCandles (CandleRequest) returns (CandleResponse);
}


message CandleRequest {
    string symbol = 1;
    string timeFrame = 2;
}

message CandleResponse {
    repeated Candle candles = 1;
}

message Candle {
   string eventType = 1;
   int64 eventTime = 2;
   string symbol = 3;
   string openTime =4; 
   string closeTime =5; 
   string openPrice = 6;
   string closePrice = 7;
   string highPrice = 8;
   string lowPrice = 9;
   string volume = 10;
   string isClose = 11;
   int32 noOfTrade = 12;
   string candleStickId = 13;
}

