import Appbar from "@/components/appComponents/Appbar";
import type { Metadata } from "next";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function BarLayout({
    children,
}: { children: React.ReactNode }) {
    return (
        <section className="relative">
            <Appbar />
            {children}
        </section>
    );
}
